name: f_limit
description: A Dart implementation of p-limit for controlling concurrency of async operations.
version: 1.0.0
homepage: https://github.com/fluttercandies/f_limit
repository: https://github.com/fluttercandies/f_limit
issue_tracker: https://github.com/fluttercandies/f_limit/issues
topics:
  - p-limit
  - future-queue
  - concurrency
  - queue
  - future

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.5
