name: f_limit
description: A Dart implementation of p-limit for controlling concurrency of async operations.
version: 1.0.1
homepage: https://github.com/fluttercandies/f_limit
repository: https://github.com/fluttercandies/f_limit
issue_tracker: https://github.com/fluttercandies/f_limit/issues
topics:
  - p-limit
  - future-queue
  - concurrency
  - queue
  - future

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
